In [4]:
import tushare as ts
df=ts.stock_pledged()

In [5]:
df.head(10)

     code  name  deals  unrest_pledged  rest_pledged     totals  p_ratio
0  000981  银亿股份    102       195955.01     129352.76  402798.99    80.76
1  002143  印纪传媒     50       142835.85          0.00  176983.42    80.71
2  000408  藏格控股     74         4708.62     149501.43  199377.95    77.35
3  000564  供销大集    123        79721.21     375042.16  600782.82    75.70
4  600828  茂业商业     81        38955.32      91531.00  173198.25    75.34
5  000662  天夏智慧     52         5690.99      55282.69   84084.44    72.51
6  000723  美锦能源    109        14532.63     279172.86  410593.21    71.53
7  000688  建新矿业     62        81188.08          0.00  113729.93    71.39
8  600053  九鼎投资    224        30744.12          0.00   43354.08    70.91
9  000038   深大通     62           11.72      36874.04   52277.74    70.56

In [6]:
df.sort_values('deals',ascending=False)

        code   name  deals  unrest_pledged  rest_pledged      totals  p_ratio
2132  601318   中国平安   2398        49350.53          0.00  1083266.45     4.56
2372  601166   兴业银行   2323        17450.62      24337.75  2077419.08     2.01
2507  000651   格力电器   1727         4853.55          0.00   601573.09     0.81
2900  000725   京东方Ａ   1635         2994.96          0.00  3386228.53     0.09
2085  300498   温氏股份   1187        23323.31       3250.48   522035.62     5.09
2815  000001   平安银行   1121         2117.02          0.00  1717041.14     0.12
1594  000333   美的集团    989        85499.30          0.00   657251.58    13.01
3176  601668   中国建筑    953         1153.86          0.00  3000000.00     0.04
1342  600016   民生银行    943       516430.91          0.00  2955176.93    17.48
2079  002466   天齐锂业    887         5943.97          0.00   114205.29     5.20
2986  600030   中信证券    838          705.31          0.00   983858.07     0.07
1197  000413   东旭光电    805        33507.93      76580.38   548025.01    20.09
2333  000750   国海证券    800         9902.92          0.00   421554.20     2.35
1363  300059   东方财富    764        73317.86          0.00   428877.97    17.10
453   002354   天神娱乐    703         4139.76      29678.40    93684.69    36.10
2151  000858    五粮液    702        16503.35          0.00   379596.67     4.35
2287  600050   中国联通    700         2424.04      84420.15  3023395.07     2.87
2746  600519   贵州茅台    674          216.15          0.00   125619.78     0.17
1770  600887   伊利股份    636        60611.81          0.00   607849.26     9.97
2581  600036   招商银行    608         9572.59          0.00  2062894.44     0.46
171   300072   三聚环保    606        62966.97      23428.51   180808.00    47.78
660   000839   中信国安    590       121612.28          0.00   391982.64    31.02
3149  601766   中国中车    584          878.99          0.00  2432779.80     0.04
431   002450    康得新    580        80485.35      49886.72   353962.48    36.83
2469  601328   交通银行    554        41558.55          0.00  3925086.40     1.06
1633  002024   苏宁云商    551        83776.04      30000.00   931003.97    12.22
1459  002594    比亚迪    551        27796.71          0.00   181314.29    15.33
381   600340   华夏幸福    551       113488.19          0.00   295494.67    38.41
2268  600109   国金证券    541         9130.42          0.00   302435.93     3.02
2325  000776   广发证券    519        14701.04          0.00   591929.15     2.48
...      ...    ...    ...             ...           ...         ...      ...
3394  600421   ST仰帆      2            1.15          0.00    19560.00     0.01
2337  603396   金辰股份      2            0.36        175.00     7555.67     2.32
3416  300731   科创新源      1            0.20          0.00     8721.74     0.00
3439  603937   丽岛新材      1            0.39          0.00    20888.00     0.00
1953  603970   中农立华      1            0.00        920.00    13333.34     6.90
2012  600710   ST常林      1         8000.00          0.00   130674.94     6.12
3446  002917    金奥博      1            0.44          0.00    11306.00     0.00
3445  002911   佛燃股份      1            0.89          0.00    55600.00     0.00
2285  000629  *ST钒钛      1            0.00      24773.23   858974.62     2.88
3345  600815  *ST厦工      1            8.03          0.00    95897.00     0.01
3448  002922    伊戈尔      1            0.30          0.00    13199.29     0.00
2136  002919   名臣健康      1            0.00        366.38     8142.38     4.50
3450  603329   上海雅仕      1            0.02          0.00    13200.00     0.00
3438  600680  *ST上普      1            0.08          0.00    25742.53     0.00
3434  600696  *ST匹凸      1            0.10          0.00    34056.56     0.00
3375  300727   润禾材料      1            1.28          0.00     9760.00     0.01
1852  600265   ST景谷      1         1136.14          0.00    12980.00     8.75
3367  002877   智能自控      1            1.36          0.00    12224.00     0.01
3433  600149  *ST坊展      1            0.34          0.00    38016.00     0.00
2658  300654   世纪天鸿      1            0.00         25.00     9335.00     0.27
3431  603848    好太太      1            0.12          0.00    40100.00     0.00
3405  000950  *ST建峰      1            0.84          0.00   172818.47     0.00
2549  600608  *ST沪科      1          190.00          0.00    32886.14     0.58
3406  300737   科顺股份      1            0.06          0.00    61066.66     0.00
1001  000803  *ST金宇      1         3002.60          0.00    12773.09    23.51
3425  603685   晨丰科技      1            0.03          0.00    10000.00     0.00
3421  300705   九典制药      1            0.20          0.00    11734.00     0.00
1589  600425  *ST青松      1        18068.38          0.00   137879.01    13.10
3415  603283   赛腾股份      1            0.08          0.00    16000.00     0.00
3419  300717   华信新材      1            0.02          0.00     6400.00     0.00

[3452 rows x 7 columns]

In [7]:
df.sort_values('p_ratio',ascending=False)

        code   name  deals  unrest_pledged  rest_pledged       totals  p_ratio
0     000981   银亿股份    102       195955.01     129352.76    402798.99    80.76
1     002143   印纪传媒     50       142835.85          0.00    176983.42    80.71
2     000408   藏格控股     74         4708.62     149501.43    199377.95    77.35
3     000564   供销大集    123        79721.21     375042.16    600782.82    75.70
4     600828   茂业商业     81        38955.32      91531.00    173198.25    75.34
5     000662   天夏智慧     52         5690.99      55282.69     84084.44    72.51
6     000723   美锦能源    109        14532.63     279172.86    410593.21    71.53
7     000688   建新矿业     62        81188.08          0.00    113729.93    71.39
8     600053   九鼎投资    224        30744.12          0.00     43354.08    70.91
9     000038    深大通     62           11.72      36874.04     52277.74    70.56
10    002356   赫美集团     30        21664.60          0.00     31047.44    69.78
11    600295   鄂尔多斯     48        42043.82          0.00     61200.00    68.70
12    002252   上海莱士    141       333938.47          0.00    497462.21    67.13
13    600246   万通地产     63        62106.87      73255.81    205400.93    65.90
14    000627   天茂集团    222        33187.18     292276.81    494062.92    65.88
15    300459   金科文化    155         6775.38     123071.82    197123.30    65.87
16    002147   新光圆成     73          205.37     119538.19    182807.64    65.50
17    002700   新疆浩源     33        27292.86          0.00     42242.69    64.61
18    002684   猛狮科技    109        17871.83      18775.46     56737.44    64.59
19    300064   豫金刚石     39        21249.42      56437.29    120547.66    64.44
20    000020   深华发A      4        11610.40          0.00     18116.54    64.09
21    000732   泰禾集团     75        79531.80          0.00    124445.07    63.91
22    300478   杭州高新     20           41.26       4219.00      6667.00    63.90
23    300317   珈伟股份     96        16347.17      38217.84     85432.94    63.87
24    002437   誉衡药业    133       140245.75          0.00    219812.30    63.80
25    300518    盛讯达     51         1302.96       4644.77      9334.00    63.72
26    600892   大晟文化     47         5192.20      30413.76     55946.42    63.64
27    600393   粤泰股份     69         8138.70     152915.23    253624.79    63.50
28    002761    多喜爱     19         1998.08       5598.96     12000.00    63.31
29    002625   光启技术     88           25.13      80172.31    126751.17    63.27
...      ...    ...    ...             ...           ...          ...      ...
3446  002917    金奥博      1            0.44          0.00     11306.00     0.00
3447  000411   英特集团      3            0.74          0.00     20744.99     0.00
3449  600062   华润双鹤     15            3.63          0.00     86936.48     0.00
3450  603329   上海雅仕      1            0.02          0.00     13200.00     0.00
3428  601998   中信银行     67           98.11          0.00   3405263.36     0.00
3429  601100   恒立液压     12            2.45          0.00     63000.00     0.00
3409  600009   上海机场     24            3.88          0.00    192695.84     0.00
3427  603605    珀莱雅      2            0.36          0.00     20000.00     0.00
3415  603283   赛腾股份      1            0.08          0.00     16000.00     0.00
3405  000950  *ST建峰      1            0.84          0.00    172818.47     0.00
3406  300737   科顺股份      1            0.06          0.00     61066.66     0.00
3407  603963   大理药业      2            0.35          0.00     10000.00     0.00
3408  000972  *ST中基      3            0.45          0.00     77128.36     0.00
3410  600540  *ST新赛      3            0.76          0.00     47092.33     0.00
3411  601086   国芳集团      5            2.41          0.00     66600.00     0.00
3412  603976   正川股份      3            0.35          0.00     10800.00     0.00
3413  600612    老凤祥      6            0.65          0.00     31710.96     0.00
3414  300735   光弘科技      2            0.25          0.00     35468.00     0.00
3416  300731   科创新源      1            0.20          0.00      8721.74     0.00
3426  601857   中国石油    173          341.97          0.00  16192207.78     0.00
3417  300723    一品红      3            0.70          0.00     16000.00     0.00
3418  000028   国药一致     17            1.20          0.00     37324.14     0.00
3419  300717   华信新材      1            0.02          0.00      6400.00     0.00
3420  300664   鹏鹞环保      8            1.00          0.00     48000.00     0.00
3421  300705   九典制药      1            0.20          0.00     11734.00     0.00
3422  600877  *ST嘉陵      4            1.57          0.00     68728.20     0.00
3423  600025   华能水电     16           70.54          0.00   1800000.00     0.00
3424  603103   横店影视      5            1.69          0.00     45300.00     0.00
3425  603685   晨丰科技      1            0.03          0.00     10000.00     0.00
3451  300732    设研院      3            0.32          0.00      7200.00     0.00

[3452 rows x 7 columns]

In [2]:
import tushare as ts
ds=ts.pledged_detail()

In [4]:
names=ds.groupby('name')

In [5]:
names

In [6]:
names['name']

In [9]:
counts=names['name'].count().sort_values(ascending=False)

In [10]:
counts.to_csv('pledged_count.csv')

In [1]:
import tushare as ts

In [3]:
bonds=ts.new_cbonds()

In [4]:
bonds

In [5]:
import pandas as pd

In [19]:
df=ts.get_k_data('300527',start='2018-01-01')

In [20]:
df

          date   open  close   high    low   volume    code
0   2018-01-02  24.18  24.03  24.28  23.94   5632.0  300527
1   2018-01-03  24.06  24.09  24.10  23.84   6233.0  300527
2   2018-01-04  24.18  24.09  24.69  23.92   9865.0  300527
3   2018-01-05  24.00  24.07  24.28  23.95   7556.0  300527
4   2018-01-08  23.98  23.89  24.01  23.45  10558.0  300527
5   2018-01-09  23.89  23.54  23.89  23.50   9115.0  300527
6   2018-01-10  23.54  23.24  23.79  23.23   7401.0  300527
7   2018-01-11  23.24  23.32  23.47  23.20   7046.0  300527
8   2018-01-12  23.33  23.28  23.50  23.15   7298.0  300527
9   2018-01-15  23.10  22.43  23.26  22.02  16814.0  300527
10  2018-01-16  22.44  22.25  22.68  22.22   6305.0  300527
11  2018-01-17  22.25  22.18  22.39  21.81   6000.0  300527
12  2018-01-18  22.32  22.33  22.78  22.18   4696.0  300527
13  2018-01-19  22.69  23.12  23.80  22.50  12243.0  300527
14  2018-01-22  23.03  23.28  23.59  22.50   9227.0  300527
15  2018-01-23  23.40  23.10  23.50  22.90   4454.0  300527
16  2018-01-24  23.10  23.05  23.19  22.81   5821.0  300527
17  2018-01-25  23.05  23.90  24.12  22.81  19167.0  300527
18  2018-01-26  23.78  24.02  24.12  23.63  10721.0  300527
19  2018-01-29  23.96  24.19  24.38  23.81  13972.0  300527
20  2018-01-30  23.95  23.98  24.44  23.95   7862.0  300527
21  2018-01-31  23.84  22.82  24.21  22.82   6229.0  300527
22  2018-02-01  22.84  22.49  23.45  22.41   6791.0  300527
23  2018-02-02  22.00  23.38  23.49  21.97   8652.0  300527
24  2018-02-05  23.59  24.99  25.15  23.03  34204.0  300527
25  2018-02-06  24.88  23.70  24.88  23.69  21584.0  300527
26  2018-02-07  23.88  23.80  24.45  23.73  22299.0  300527
27  2018-02-08  23.50  23.30  24.00  23.29  10627.0  300527
28  2018-02-09  22.49  22.60  22.80  21.01  22756.0  300527
29  2018-02-12  22.70  22.49  22.76  22.21   9043.0  300527
30  2018-02-13  22.74  22.49  22.78  22.33   5659.0  300527
31  2018-02-14  22.54  22.34  22.64  21.90   7146.0  300527
32  2018-02-22  22.60  22.72  22.95  22.20   5435.0  300527
33  2018-02-23  22.73  22.58  22.93  22.35   3104.0  300527
34  2018-02-26  22.59  23.21  23.50  22.50  17026.0  300527
35  2018-02-27  22.93  22.73  23.50  22.50  26854.0  300527

In [8]:
df['name']=u'华舟应急'

In [21]:
df.set_index('date',inplace=True)

In [22]:
df

             open  close   high    low   volume    code
date
2018-01-02  24.18  24.03  24.28  23.94   5632.0  300527
2018-01-03  24.06  24.09  24.10  23.84   6233.0  300527
2018-01-04  24.18  24.09  24.69  23.92   9865.0  300527
2018-01-05  24.00  24.07  24.28  23.95   7556.0  300527
2018-01-08  23.98  23.89  24.01  23.45  10558.0  300527
2018-01-09  23.89  23.54  23.89  23.50   9115.0  300527
2018-01-10  23.54  23.24  23.79  23.23   7401.0  300527
2018-01-11  23.24  23.32  23.47  23.20   7046.0  300527
2018-01-12  23.33  23.28  23.50  23.15   7298.0  300527
2018-01-15  23.10  22.43  23.26  22.02  16814.0  300527
2018-01-16  22.44  22.25  22.68  22.22   6305.0  300527
2018-01-17  22.25  22.18  22.39  21.81   6000.0  300527
2018-01-18  22.32  22.33  22.78  22.18   4696.0  300527
2018-01-19  22.69  23.12  23.80  22.50  12243.0  300527
2018-01-22  23.03  23.28  23.59  22.50   9227.0  300527
2018-01-23  23.40  23.10  23.50  22.90   4454.0  300527
2018-01-24  23.10  23.05  23.19  22.81   5821.0  300527
2018-01-25  23.05  23.90  24.12  22.81  19167.0  300527
2018-01-26  23.78  24.02  24.12  23.63  10721.0  300527
2018-01-29  23.96  24.19  24.38  23.81  13972.0  300527
2018-01-30  23.95  23.98  24.44  23.95   7862.0  300527
2018-01-31  23.84  22.82  24.21  22.82   6229.0  300527
2018-02-01  22.84  22.49  23.45  22.41   6791.0  300527
2018-02-02  22.00  23.38  23.49  21.97   8652.0  300527
2018-02-05  23.59  24.99  25.15  23.03  34204.0  300527
2018-02-06  24.88  23.70  24.88  23.69  21584.0  300527
2018-02-07  23.88  23.80  24.45  23.73  22299.0  300527
2018-02-08  23.50  23.30  24.00  23.29  10627.0  300527
2018-02-09  22.49  22.60  22.80  21.01  22756.0  300527
2018-02-12  22.70  22.49  22.76  22.21   9043.0  300527
2018-02-13  22.74  22.49  22.78  22.33   5659.0  300527
2018-02-14  22.54  22.34  22.64  21.90   7146.0  300527
2018-02-22  22.60  22.72  22.95  22.20   5435.0  300527
2018-02-23  22.73  22.58  22.93  22.35   3104.0  300527
2018-02-26  22.59  23.21  23.50  22.50  17026.0  300527
2018-02-27  22.93  22.73  23.50  22.50  26854.0  300527

In [25]:
s=pd.Series(u'华舟应急',df.index)

In [26]:
s

date
2018-01-02    华舟应急
2018-01-03    华舟应急
2018-01-04    华舟应急
2018-01-05    华舟应急
2018-01-08    华舟应急
2018-01-09    华舟应急
2018-01-10    华舟应急
2018-01-11    华舟应急
2018-01-12    华舟应急
2018-01-15    华舟应急
2018-01-16    华舟应急
2018-01-17    华舟应急
2018-01-18    华舟应急
2018-01-19    华舟应急
2018-01-22    华舟应急
2018-01-23    华舟应急
2018-01-24    华舟应急
2018-01-25    华舟应急
2018-01-26    华舟应急
2018-01-29    华舟应急
2018-01-30    华舟应急
2018-01-31    华舟应急
2018-02-01    华舟应急
2018-02-02    华舟应急
2018-02-05    华舟应急
2018-02-06    华舟应急
2018-02-07    华舟应急
2018-02-08    华舟应急
2018-02-09    华舟应急
2018-02-12    华舟应急
2018-02-13    华舟应急
2018-02-14    华舟应急
2018-02-22    华舟应急
2018-02-23    华舟应急
2018-02-26    华舟应急
2018-02-27    华舟应急
dtype: object

In [28]:
df.drop('high',axis=1,inplace=True)

In [29]:
df

             open  close    low   volume    code
date
2018-01-02  24.18  24.03  23.94   5632.0  300527
2018-01-03  24.06  24.09  23.84   6233.0  300527
2018-01-04  24.18  24.09  23.92   9865.0  300527
2018-01-05  24.00  24.07  23.95   7556.0  300527
2018-01-08  23.98  23.89  23.45  10558.0  300527
2018-01-09  23.89  23.54  23.50   9115.0  300527
2018-01-10  23.54  23.24  23.23   7401.0  300527
2018-01-11  23.24  23.32  23.20   7046.0  300527
2018-01-12  23.33  23.28  23.15   7298.0  300527
2018-01-15  23.10  22.43  22.02  16814.0  300527
2018-01-16  22.44  22.25  22.22   6305.0  300527
2018-01-17  22.25  22.18  21.81   6000.0  300527
2018-01-18  22.32  22.33  22.18   4696.0  300527
2018-01-19  22.69  23.12  22.50  12243.0  300527
2018-01-22  23.03  23.28  22.50   9227.0  300527
2018-01-23  23.40  23.10  22.90   4454.0  300527
2018-01-24  23.10  23.05  22.81   5821.0  300527
2018-01-25  23.05  23.90  22.81  19167.0  300527
2018-01-26  23.78  24.02  23.63  10721.0  300527
2018-01-29  23.96  24.19  23.81  13972.0  300527
2018-01-30  23.95  23.98  23.95   7862.0  300527
2018-01-31  23.84  22.82  22.82   6229.0  300527
2018-02-01  22.84  22.49  22.41   6791.0  300527
2018-02-02  22.00  23.38  21.97   8652.0  300527
2018-02-05  23.59  24.99  23.03  34204.0  300527
2018-02-06  24.88  23.70  23.69  21584.0  300527
2018-02-07  23.88  23.80  23.73  22299.0  300527
2018-02-08  23.50  23.30  23.29  10627.0  300527
2018-02-09  22.49  22.60  21.01  22756.0  300527
2018-02-12  22.70  22.49  22.21   9043.0  300527
2018-02-13  22.74  22.49  22.33   5659.0  300527
2018-02-14  22.54  22.34  21.90   7146.0  300527
2018-02-22  22.60  22.72  22.20   5435.0  300527
2018-02-23  22.73  22.58  22.35   3104.0  300527
2018-02-26  22.59  23.21  22.50  17026.0  300527
2018-02-27  22.93  22.73  22.50  26854.0  300527

In [30]:
ts.get_deposit_rate()

           date            deposit_type   rate
0    2015-10-24                定活两便(定期)     --
1    2015-10-24            定期存款整存整取(半年)   1.30
2    2015-10-24            定期存款整存整取(二年)   2.10
3    2015-10-24           定期存款整存整取(三个月)   1.10
4    2015-10-24            定期存款整存整取(三年)   2.75
5    2015-10-24            定期存款整存整取(五年)     --
6    2015-10-24            定期存款整存整取(一年)   1.50
7    2015-10-24               活期存款(不定期)   0.35
8    2015-10-24  零存整取、整存零取、存本取息定期存款(三年)   1.30
9    2015-10-24  零存整取、整存零取、存本取息定期存款(五年)     --
10   2015-10-24  零存整取、整存零取、存本取息定期存款(一年)   1.10
11   2015-10-24                通知存款(七天)   1.35
12   2015-10-24                通知存款(一天)   0.80
13   2015-10-24                协定存款(定期)   1.15
14   2015-08-26                定活两便(定期)     --
15   2015-08-26            定期存款整存整取(半年)   1.55
16   2015-08-26            定期存款整存整取(二年)   2.35
17   2015-08-26           定期存款整存整取(三个月)   1.35
18   2015-08-26            定期存款整存整取(三年)   3.00
19   2015-08-26            定期存款整存整取(五年)     --
20   2015-08-26            定期存款整存整取(一年)   1.75
21   2015-08-26               活期存款(不定期)   0.35
22   2015-08-26  零存整取、整存零取、存本取息定期存款(三年)   1.55
23   2015-08-26  零存整取、整存零取、存本取息定期存款(五年)     --
24   2015-08-26  零存整取、整存零取、存本取息定期存款(一年)   1.35
25   2015-08-26                通知存款(七天)   1.35
26   2015-08-26                通知存款(一天)   0.80
27   2015-08-26                协定存款(定期)   1.15
28   2015-06-28                定活两便(定期)     --
29   2015-06-28            定期存款整存整取(半年)   1.80
..          ...                     ...    ...
516  1990-08-21                通知存款(一天)     --
517  1990-08-21                协定存款(定期)     --
518  1990-04-15                定活两便(定期)     --
519  1990-04-15            定期存款整存整取(半年)   7.74
520  1990-04-15            定期存款整存整取(二年)  11.00
521  1990-04-15           定期存款整存整取(三个月)   6.30
522  1990-04-15            定期存款整存整取(三年)  11.88
523  1990-04-15            定期存款整存整取(五年)  13.68
524  1990-04-15            定期存款整存整取(一年)  10.08
525  1990-04-15               活期存款(不定期)   2.88
526  1990-04-15  零存整取、整存零取、存本取息定期存款(三年)     --
527  1990-04-15  零存整取、整存零取、存本取息定期存款(五年)     --
528  1990-04-15  零存整取、整存零取、存本取息定期存款(一年)     --
529  1990-04-15                通知存款(七天)     --
530  1990-04-15                通知存款(一天)     --
531  1990-04-15                协定存款(定期)     --
532  1989-02-01                定活两便(定期)     --
533  1989-02-01            定期存款整存整取(半年)   9.00
534  1989-02-01            定期存款整存整取(二年)  12.20
535  1989-02-01           定期存款整存整取(三个月)   7.56
536  1989-02-01            定期存款整存整取(三年)  13.14
537  1989-02-01            定期存款整存整取(五年)  14.94
538  1989-02-01            定期存款整存整取(一年)  11.34
539  1989-02-01               活期存款(不定期)   2.88
540  1989-02-01  零存整取、整存零取、存本取息定期存款(三年)     --
541  1989-02-01  零存整取、整存零取、存本取息定期存款(五年)     --
542  1989-02-01  零存整取、整存零取、存本取息定期存款(一年)     --
543  1989-02-01                通知存款(七天)     --
544  1989-02-01                通知存款(一天)     --
545  1989-02-01                协定存款(定期)     --

[546 rows x 3 columns]

In [31]:
ts.get_loan_rate()

           date            loan_type   rate
0    2015-10-24          短期贷款(六个月以内)   4.35
1    2015-10-24         短期贷款(六个月至一年)   4.35
2    2015-10-24          中长期贷款(三至五年)   4.75
3    2015-10-24          中长期贷款(五年以上)   4.90
4    2015-10-24          中长期贷款(一至三年)   4.75
5    2015-10-24               贴现(贴现)     --
6    2015-10-24         优惠贷款(扶贫贴息贷款)     --
7    2015-10-24     优惠贷款(老少边穷发展经济贷款)     --
8    2015-10-24     优惠贷款(民政部门福利工厂贷款)     --
9    2015-10-24  优惠贷款(民族贸易及民族用品生产贷款)     --
10   2015-10-24       优惠贷款(贫困县办工业贷款)     --
11   2015-10-24      个人住房商业贷款(六个月以内)   3.92
12   2015-10-24     个人住房商业贷款(六个月至一年)   3.92
13   2015-10-24       个人住房商业贷款(三至五年)   4.28
14   2015-10-24       个人住房商业贷款(五年以上)   4.41
15   2015-10-24       个人住房商业贷款(一至三年)   4.28
16   2015-10-24      个人住房公积金贷款(五年以上)   3.25
17   2015-10-24      个人住房公积金贷款(五年以下)   2.75
18   2015-09-06            再贴现(再贴现率)   2.25
19   2015-08-26          短期贷款(六个月以内)   4.60
20   2015-08-26         短期贷款(六个月至一年)   4.60
21   2015-08-26          中长期贷款(三至五年)   5.00
22   2015-08-26          中长期贷款(五年以上)   5.15
23   2015-08-26          中长期贷款(一至三年)   5.00
24   2015-08-26               贴现(贴现)     --
25   2015-08-26         优惠贷款(扶贫贴息贷款)     --
26   2015-08-26     优惠贷款(老少边穷发展经济贷款)     --
27   2015-08-26     优惠贷款(民政部门福利工厂贷款)     --
28   2015-08-26  优惠贷款(民族贸易及民族用品生产贷款)     --
29   2015-08-26       优惠贷款(贫困县办工业贷款)     --
..          ...                  ...    ...
770  1993-05-15      个人住房公积金贷款(五年以上)     --
771  1993-05-15      个人住房公积金贷款(五年以下)     --
772  1993-05-12         特种贷款(特种贷款利率)  11.25
773  1991-04-21          短期贷款(六个月以内)   8.10
774  1991-04-21         短期贷款(六个月至一年)   8.64
775  1991-04-21          中长期贷款(三至五年)   9.54
776  1991-04-21          中长期贷款(五年以上)   9.72
777  1991-04-21          中长期贷款(一至三年)   9.00
778  1991-04-21               贴现(贴现)     --
779  1991-04-21         优惠贷款(扶贫贴息贷款)   2.88
780  1991-04-21     优惠贷款(老少边穷发展经济贷款)   5.76
781  1991-04-21     优惠贷款(民政部门福利工厂贷款)   7.20
782  1991-04-21  优惠贷款(民族贸易及民族用品生产贷款)   5.76
783  1991-04-21       优惠贷款(贫困县办工业贷款)   5.76
784  1991-04-21      个人住房商业贷款(六个月以内)   7.29
785  1991-04-21     个人住房商业贷款(六个月至一年)   7.78
786  1991-04-21       个人住房商业贷款(三至五年)   8.59
787  1991-04-21       个人住房商业贷款(五年以上)   8.75
788  1991-04-21       个人住房商业贷款(一至三年)   8.10
789  1991-04-21      个人住房公积金贷款(五年以上)     --
790  1991-04-21      个人住房公积金贷款(五年以下)     --
791  1991-04-21         特种贷款(特种贷款利率)   9.72
792  1990-08-21          短期贷款(六个月以内)   8.64
793  1990-08-21         短期贷款(六个月至一年)   9.36
794  1990-08-21          中长期贷款(三至五年)  10.80
795  1990-08-21          中长期贷款(五年以上)  11.16
796  1990-08-21          中长期贷款(一至三年)  10.08
797  1990-08-21               贴现(贴现)     --
798  1990-08-21         优惠贷款(扶贫贴息贷款)     --
799  1990-08-21     优惠贷款(老少边穷发展经济贷款)     --

[800 rows x 3 columns]

In [1]:
import tushare as ts
base_info = ts.get_stock_basics()
current_prices = ts.get_today_all()

[Getting data:]############################################################

In [3]:
current_prices.head()

,code,name,changepercent,trade,open,high,low,settlement,volume,turnoverratio,amount,per,pb,mktcap,nmc
0,603999,读者传媒,-1.992,7.38,7.52,7.52,7.33,7.53,1819412,0.78968,13483307,25.448,2.548,4.250880e+05,1.700352e+05
1,603998,方盛制药,0.000,9.43,0.00,0.00,0.00,9.43,0,0.00000,0,58.938,4.066,4.063731e+05,4.009605e+05
2,603997,继峰股份,-1.023,11.61,11.70,11.76,11.60,11.73,2221242,0.35258,25870105,19.678,4.435,7.403920e+05,7.314300e+05
3,603996,中新科技,-0.174,17.24,17.22,17.39,17.07,17.27,891400,0.86313,15308372,44.205,3.643,5.174586e+05,1.780461e+05
4,603993,洛阳钼业,-1.828,9.13,9.28,9.66,9.07,9.30,391591469,3.02300,3666606011,152.167,5.290,1.972011e+07,1.182676e+07

In [16]:
base_info.loc['000625']['bvps']

numpy.float64

In [26]:
current_prices[current_prices['code']=='000625']['trade'].values[0]

12.08

In [33]:
count=0
for i in current_prices['code']:
    if base_info.loc[i]['bvps']>=current_prices[current_prices['code'] == i]['trade'].values[0]:
        print base_info.loc[i]['name']
        
        count=count+1
print count

中信银行
中国银行
中煤能源
光大银行
交通银行
上海银行
北京银行
兴业银行
四川成渝
郴电国际
江苏银行
哈投股份
世茂股份
东方集团
悦达投资
信达地产
黑牡丹
上海能源
赣粤高速
北京城建
南山铝业
福田汽车
华电国际
中远海能
民生银行
华夏银行
浦发银行
朗新科技
科锐国际
中孚信息
民德电子
德艺文创
万兴科技
新雷能
美联新材
会畅通讯
通合科技
星徽精密
赢合科技
康拓红外
双杰电气
鲍斯股份
航新科技
金盾股份
正业科技
道氏技术
腾信股份
天华超净
光环新网
光一科技
麦迪电气
银邦股份
德威新材
珈伟股份
邦讯技术
荣科科技
南通锻压
华昌达
兴源环境
飞力达
冠昊生物
金力泰
纳川股份
智慧松德
新研股份
神雾环保
汤臣倍健
大富科技
锦富技术
坚瑞沃能
达刚路机
盛运环保
文化长城
康芝药业
华谊嘉信
安诺其
豫金刚石
三维丝
福瑞股份
梅泰诺
金龙机电
南风股份
香山股份
传艺科技
三晖电气
麦格米特
环球印务
科迪乳业
蓝黛传动
万达电影
中矿资源
龙大肉食
金一文化
美盛文化
睿康股份
京威股份
克明面业
摩登大道
加加食品
民盛金科
融钰集团
艾格拉斯
亚夏汽车
ST龙力
八菱科技
西陇科学
圣阳股份
群兴玩具
东方铁塔
司尔特
新界泵业
光正集团
天桥起重
日发精机
金字火腿
天广中茂
涪陵榨菜
众应互联
摩恩电气
康得新
晨鑫科技
龙星化工
誉衡药业
ST尤夫
中原特钢
雷科防务
雅克科技
建研集团
东山精密
台海核电
富临运业
潮宏基
新纶科技
华英农业
*ST三泰
中利集团
齐心集团
大 东 南
德奥通航
升达林业
兆新股份
上海莱士
恒康医疗
特 尔 佳
南洋股份
嘉应制药
海得控制
深圳惠程
中航三鑫
远 望 谷
新光圆成
印纪传媒
麦达数字
天马股份
科陆电子
天润数娱
广博股份
浔兴股份
万丰奥威
万邦德
沙钢股份
凯瑞德
宝鹰股份
旺能环境
德豪润达
豫能控股
隆平高科
东方钽业
*ST建峰
凯迪生态
中粮生化
*ST天化
现代投资
吉电股份
华茂股份
神雾节能
陕西金叶
*ST新城
凯撒旅游
华闻传媒
通化金马
浩物股份
河钢股份
恒逸石化
*ST华泽
经纬纺机
永安林业
*ST钒钛
海航投资
*ST东海A
神州易桥
黔轮胎Ａ
海马汽车
海南海药
供销大集
神州信息
航天发展
皖能电力
中天金融
华映科技
万泽股份
万 家 乐
美菱电器
国际医学
*ST烯碳
华塑控股
中润资源
湖北宜化
渤海金控
中联重科
华数传媒
皇庭国际
泛海控股
深大通
中国天楹
神州数码
中粮地产
深深房Ａ
深赤湾Ａ
深深宝Ａ

KeyError: u'the label [900951] is not in the [index]'

In [4]:
import tushare as ts
debt = ts.new_cbonds(default=0)

#####

In [5]:
debt

,bcode,bname,scode,sname,xcode,amount,marketprice,convprice,firstdayprice,ipo_date,issue_date,ballot,return,perreturn
0,128037,岩土转债,002542,中化岩土,072542,6.04,NaN,8.05,NaN,2018-03-15,NaN,NaN,NaN,NaN
1,127006,敖东转债,000623,吉林敖东,070623,24.13,NaN,21.12,NaN,2018-03-13,NaN,0.12%,NaN,80.80
2,127005,长证转债,000783,长江证券,070783,50.00,NaN,7.60,NaN,2018-03-12,NaN,NaN,NaN,NaN
3,128036,金农转债,002548,金新农,072548,6.50,NaN,9.72,NaN,2018-03-09,NaN,0.05%,NaN,NaN
4,123009,星源转债,300568,星源材质,370568,4.80,NaN,27.99,NaN,2018-03-07,NaN,0.04%,NaN,244.49
5,113505,杭电转债,603618,杭电股份,754618,7.80,NaN,7.29,NaN,2018-03-06,NaN,0.08%,NaN,118.57
6,113504,艾华转债,603989,艾华集团,754989,6.91,NaN,36.59,NaN,2018-03-02,NaN,0.02%,NaN,457.45
7,113019,玲珑转债,601966,玲珑轮胎,783966,20.00,NaN,19.10,NaN,2018-03-01,NaN,0.21%,NaN,47.21
8,128035,大族转债,002008,大族激光,072008,23.00,119.55,52.70,116.34,2018-02-06,2018-03-05,0.20%,0.02%,51.07
9,132015,18中油EB,601857,中国石油,759000,200.00,NaN,9.38,NaN,2018-02-01,NaN,30.00%,NaN,3.05
10,123008,康泰转债,300601,康泰生物,370601,3.56,NaN,47.01,NaN,2018-02-01,2018-03-19,0.03%,NaN,387.05
11,110043,无锡转债,600908,无锡银行,733908,30.00,96.89,8.90,97.43,2018-01-30,2018-03-14,0.19%,0.00%,53.15
12,128034,江银转债,002807,江阴银行,072807,20.00,96.01,9.16,97.76,2018-01-26,2018-02-14,0.14%,0.00%,72.00
13,113018,常熟转债,601128,常熟银行,783128,30.00,103.94,7.61,107.91,2018-01-19,2018-02-06,0.19%,0.01%,51.99
14,123007,道氏转债,300409,道氏技术,370409,4.80,117.05,45.21,118.00,2017-12-28,2018-01-26,0.07%,0.01%,139.22
15,113017,吉视转债,601929,吉视传媒,783929,15.60,101.30,2.98,98.08,2017-12-27,2018-01-15,0.40%,0.01%,0.10
16,128033,迪龙转债,002658,雪迪龙,072658,5.20,100.33,13.35,104.00,2017-12-27,2018-01-29,0.04%,0.00%,258.40
17,110042,航电转债,600372,中航电子,733372,24.00,103.98,14.29,101.76,2017-12-25,2018-01-15,0.20%,0.01%,50.80
18,128032,双环转债,002472,双环传动,072472,10.00,103.92,10.07,104.75,2017-12-25,2018-01-25,NaN,NaN,NaN
19,110041,蒙电转债,600863,内蒙华电,733863,18.75,103.00,2.95,104.18,2017-12-22,2018-01-09,0.27%,0.01%,37.51
20,128029,太阳转债,002078,太阳纸业,072078,12.00,135.30,8.85,NaN,2017-12-22,2018-01-16,0.04%,NaN,232.16
21,128030,天康转债,002100,天康生物,072100,10.00,103.53,8.25,109.01,2017-12-22,2018-01-29,0.06%,0.01%,161.76
22,128028,赣锋转债,002460,赣锋锂业,072460,9.28,118.85,71.89,102.21,2017-12-21,2018-01-19,0.06%,0.00%,163.17
23,123006,东财转债,300059,东方财富,370059,46.50,118.85,13.69,121.65,2017-12-20,2018-01-29,0.40%,0.10%,24.78
24,123005,万信转债,300168,万达信息,370168,9.00,120.01,13.11,108.00,2017-12-19,2018-01-30,0.08%,0.01%,123.99
25,123004,铁汉转债,300197,铁汉生态,370197,11.00,101.89,12.39,107.63,2017-12-18,2018-01-26,0.06%,0.00%,168.26
26,128027,崇达转债,002815,崇达技术,072815,8.00,107.50,30.93,106.70,2017-12-15,2018-01-22,0.02%,0.00%,534.99
27,113503,泰晶转债,603738,泰晶科技,754738,2.15,107.56,25.41,101.80,2017-12-15,2018-01-02,0.01%,0.00%,1069.65
28,128026,众兴转债,002772,众兴菌业,072772,9.20,96.75,11.74,99.69,2017-12-13,2018-01-03,0.06%,0.00%,177.63
29,123003,蓝思转债,300433,蓝思科技,370433,48.00,99.00,36.59,95.71,2017-12-08,2018-01-17,0.33%,-0.02%,30.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,125959,首钢转债,000959,首钢股份,70959.0,20.00,205.00,2.97,102.20,2003-12-16,2003-12-31,18.45%,0.58%,NaN
175,110001,邯钢转债,600001,邯郸钢铁,733001.0,20.00,182.00,3.36,103.55,2003-11-26,2003-12-11,13.28%,0.53%,0.75
176,100196,复星转债,600196,复星医药,733196.0,9.50,138.20,5.03,99.00,2003-10-28,2003-11-17,25.47%,-0.03%,0.39
177,100096,云化转债,600096,云天化,733096.0,4.10,147.21,5.80,100.12,2003-09-10,2003-09-25,0.80%,0.00%,12.49
178,125936,华西转债,000936,华西村,70936.0,4.00,143.98,2.70,100.68,2003-09-01,2003-09-16,0.70%,0.01%,14.34
179,100117,西钢转债,600117,西宁特钢,733117.0,4.90,158.00,4.85,103.31,2003-08-11,2003-08-26,0.76%,0.03%,13.17
180,100795,国电转债,600795,国电电力,733795.0,20.00,211.88,2.27,108.04,2003-07-18,2003-08-01,0.35%,0.03%,28.73
181,100236,桂冠转债,600236,桂冠电力,733236.0,8.00,128.50,5.77,103.00,2003-06-30,2003-07-15,1.36%,0.05%,7.37
182,100567,山鹰转债,600567,山鹰纸业,733567.0,2.50,120.37,2.46,102.24,2003-06-16,2003-07-01,1.11%,0.02%,9.02
183,100726,华电转债,600726,华电能源,733726.0,8.00,299.98,3.10,108.00,2003-06-03,2003-06-18,0.63%,0.04%,15.95
184,125630,铜都转债,000630,铜陵有色,70630.0,7.60,112.40,4.45,109.45,2003-05-21,2003-06-04,0.89%,0.08%,11.17
185,125930,丰原转债,000930,丰原生化,70930.0,5.00,145.01,2.40,104.29,2003-04-24,2003-05-20,1.36%,0.07%,7.36
186,100177,雅戈转债,600177,雅戈尔,733177.0,11.90,119.23,3.35,109.88,2003-04-03,2003-04-21,0.50%,0.04%,19.87
187,100016,民生转债,600016,民生银行,733016.0,40.00,98.68,2.39,100.01,2003-02-27,2003-03-18,87.86%,-0.11%,0.11
188,125629,钢钒转债,000629,攀钢钢钒,70629.0,16.00,144.50,5.64,NaN,2003-01-22,2003-02-17,100.00%,NaN,NaN
189,125729,燕京转债,000729,燕京啤酒,70729.0,7.00,129.80,21.66,NaN,2002-10-16,2002-10-31,100.00%,NaN,NaN
190,126301,丝绸转2,000301,丝绸股份,76301.0,8.00,138.70,3.00,NaN,2002-09-09,2002-09-24,100.00%,NaN,NaN
191,100087,水运转债,600087,长航油运,733087.0,3.20,205.10,5.41,NaN,2002-08-13,2002-08-28,79.46%,NaN,0.13
192,125002,万科转债,000002,万科A,70002.0,15.00,145.33,5.85,NaN,2002-06-13,2002-06-28,38.19%,NaN,0.26
193,100220,阳光转债,600220,江苏阳光,733220.0,8.30,101.99,3.80,NaN,2002-04-18,2002-05-16,7.19%,NaN,1.39
194,125898,鞍钢转债,000898,鞍钢股份,5898.0,15.00,116.65,2.83,99.20,2000-03-17,2000-04-17,79.27%,0.79%,0.13
195,100009,机场转债,600009,上海机场,733009.0,13.50,153.85,7.69,101.06,2000-03-02,2000-03-16,4.71%,-4.62%,2.12
196,125301,丝绸转债,000301,丝绸股份,5301.0,2.00,303.59,4.10,203.80,1998-08-28,1998-09-15,1.25%,1.26%,NaN
197,100001,南化转债,600301,南化股份,733001.0,1.50,269.70,4.56,229.00,1998-08-03,1998-09-02,0.14%,0.18%,73.55
198,132013,17宝武EB,600019,宝钢股份,000nan,150.00,105.36,10.00,97.01,NaN,2017-12-28,NaN,NaN,NaN
199,110488,天药转债,600488,天药股份,000nan,3.90,189.73,4.33,107.18,NaN,2006-11-10,NaN,NaN,NaN
200,110021,上电转债,600021,上海电力,000nan,10.00,226.58,4.43,113.79,NaN,2006-12-19,NaN,NaN,NaN
201,115002,国安债1,000839,中信国安,000nan,17.00,99.88,NaN,70.50,NaN,2007-09-25,NaN,NaN,NaN
202,125009,宝安转券,000009,中国宝安,000nan,5.00,NaN,19.39,NaN,NaN,1993-02-10,NaN,NaN,NaN
203,125024,招商转债,000024,招商地产,000nan,15.10,290.37,13.09,122.00,NaN,2006-09-11,NaN,NaN,NaN

In [3]:
debt.dropna(subset=['marketprice'])

,bcode,bname,scode,sname,xcode,amount,marketprice,convprice,firstdayprice,ipo_date,issue_date,ballot,return,perreturn
8,128035,大族转债,002008,大族激光,072008,23.00,119.55,52.70,116.34,2018-02-06,2018-03-05,0.20%,0.02%,51.07
11,110043,无锡转债,600908,无锡银行,733908,30.00,96.89,8.90,97.43,2018-01-30,2018-03-14,0.19%,0.00%,53.15
12,128034,江银转债,002807,江阴银行,072807,20.00,96.01,9.16,97.76,2018-01-26,2018-02-14,0.14%,0.00%,72.00
13,113018,常熟转债,601128,常熟银行,783128,30.00,103.94,7.61,107.91,2018-01-19,2018-02-06,0.19%,0.01%,51.99
14,123007,道氏转债,300409,道氏技术,370409,4.80,117.05,45.21,118.00,2017-12-28,2018-01-26,0.07%,0.01%,139.22
15,113017,吉视转债,601929,吉视传媒,783929,15.60,101.30,2.98,98.08,2017-12-27,2018-01-15,0.40%,0.01%,0.10
16,128033,迪龙转债,002658,雪迪龙,072658,5.20,100.33,13.35,104.00,2017-12-27,2018-01-29,0.04%,0.00%,258.40
17,110042,航电转债,600372,中航电子,733372,24.00,103.98,14.29,101.76,2017-12-25,2018-01-15,0.20%,0.01%,50.80
18,128032,双环转债,002472,双环传动,072472,10.00,103.92,10.07,104.75,2017-12-25,2018-01-25,NaN,NaN,NaN
19,110041,蒙电转债,600863,内蒙华电,733863,18.75,103.00,2.95,104.18,2017-12-22,2018-01-09,0.27%,0.01%,37.51
20,128029,太阳转债,002078,太阳纸业,072078,12.00,135.30,8.85,NaN,2017-12-22,2018-01-16,0.04%,NaN,232.16
21,128030,天康转债,002100,天康生物,072100,10.00,103.53,8.25,109.01,2017-12-22,2018-01-29,0.06%,0.01%,161.76
22,128028,赣锋转债,002460,赣锋锂业,072460,9.28,118.85,71.89,102.21,2017-12-21,2018-01-19,0.06%,0.00%,163.17
23,123006,东财转债,300059,东方财富,370059,46.50,118.85,13.69,121.65,2017-12-20,2018-01-29,0.40%,0.10%,24.78
24,123005,万信转债,300168,万达信息,370168,9.00,120.01,13.11,108.00,2017-12-19,2018-01-30,0.08%,0.01%,123.99
25,123004,铁汉转债,300197,铁汉生态,370197,11.00,101.89,12.39,107.63,2017-12-18,2018-01-26,0.06%,0.00%,168.26
26,128027,崇达转债,002815,崇达技术,072815,8.00,107.50,30.93,106.70,2017-12-15,2018-01-22,0.02%,0.00%,534.99
27,113503,泰晶转债,603738,泰晶科技,754738,2.15,107.56,25.41,101.80,2017-12-15,2018-01-02,0.01%,0.00%,1069.65
28,128026,众兴转债,002772,众兴菌业,072772,9.20,96.75,11.74,99.69,2017-12-13,2018-01-03,0.06%,0.00%,177.63
29,123003,蓝思转债,300433,蓝思科技,370433,48.00,99.00,36.59,95.71,2017-12-08,2018-01-17,0.33%,-0.02%,30.27
30,128025,特一转债,002728,特一药业,072728,3.54,100.67,20.20,NaN,2017-12-06,2017-12-27,0.01%,NaN,1858.01
31,128024,宁行转债,002142,宁波银行,072142,100.00,117.80,18.45,112.38,2017-12-05,2018-01-12,0.05%,0.01%,191.53
32,128023,亚太转债,002284,亚太股份,072284,10.00,94.80,10.44,95.09,2017-12-04,2017-12-26,0.02%,0.00%,407.54
33,128022,众信转债,002707,众信旅游,072707,7.00,119.10,11.12,101.52,2017-12-01,2017-12-28,0.00%,0.00%,2964.06
34,128021,兄弟转债,002562,兄弟科技,072562,7.00,102.20,18.17,99.90,2017-11-28,2017-12-27,0.00%,0.00%,7493.74
35,110040,生益转债,600183,生益科技,733183,18.00,113.66,17.34,99.99,2017-11-24,2017-12-11,0.01%,0.00%,1767.25
36,123002,国祯转债,300388,国祯环保,370388,5.97,110.20,21.04,113.80,2017-11-24,2017-12-25,0.00%,0.00%,2573.62
37,110039,宝信转债,600845,宝信软件,733845,16.00,128.87,18.36,96.90,2017-11-17,2017-12-05,0.01%,0.00%,1267.86
38,128020,水晶转债,002273,水晶光电,072273,11.80,99.05,29.90,100.50,2017-11-17,2017-12-12,0.00%,0.00%,2259.55
39,110038,济川转债,600566,济川药业,733566,8.43,116.87,41.04,101.75,2017-11-13,2017-11-29,0.01%,0.00%,864.21
40,113502,嘉澳转债,603822,嘉澳环保,754822,1.85,98.71,45.48,122.80,2017-11-10,2017-11-27,0.00%,0.00%,7277.21
41,128019,久立转2,002318,久立特材,072318,10.40,98.10,8.37,100.04,2017-11-08,2017-12-01,0.01%,0.00%,1968.62
42,113016,小康转债,601127,小康股份,783127,15.00,100.16,23.00,110.84,2017-11-06,2017-11-21,0.00%,0.00%,3431.17
43,128018,时达转债,002527,新时达,072527,8.83,96.04,11.90,96.58,2017-11-06,2017-12-04,0.00%,0.00%,2456.65
44,113015,隆基转债,601012,隆基股份,783012,28.00,121.14,32.35,130.32,2017-11-02,2017-11-20,0.01%,0.00%,111.04
45,128017,金禾转债,002597,金禾实业,072597,6.00,126.20,23.92,116.55,2017-11-01,2017-11-27,0.00%,0.00%,7856.42
46,113014,林洋转债,601222,林洋能源,783222,30.00,107.43,8.80,120.55,2017-10-27,2017-11-13,0.00%,0.00%,3394.59
47,128016,雨虹转债,002271,东方雨虹,072271,18.40,123.00,38.48,120.12,2017-09-25,2017-10-20,0.00%,0.00%,7582.68
48,113013,国君转债,601211,国泰君安,783211,70.00,106.69,20.20,120.01,2017-07-07,2017-07-24,0.08%,0.01%,123.50
49,128015,久其转债,002279,久其软件,072279,7.80,106.70,12.90,116.10,2017-06-08,2017-06-27,2.38%,0.41%,4.20

In [9]:
conn=ts.get_apis()
df= ts.tick('300433',conn=conn,date='2018-03-15')

In [10]:
df

              datetime  price  vol  type
0     2018-03-15 09:25  28.45  375     2
1     2018-03-15 09:30  28.37  288     1
2     2018-03-15 09:30  28.37  280     0
3     2018-03-15 09:30  28.37   54     0
4     2018-03-15 09:30  28.40  195     0
5     2018-03-15 09:30  28.39    9     1
6     2018-03-15 09:30  28.40   14     0
7     2018-03-15 09:30  28.39   33     1
8     2018-03-15 09:30  28.40   29     0
9     2018-03-15 09:30  28.39    1     1
10    2018-03-15 09:30  28.40    1     0
11    2018-03-15 09:30  28.45  567     0
12    2018-03-15 09:30  28.45    9     1
13    2018-03-15 09:30  28.48   72     0
14    2018-03-15 09:30  28.48   67     0
15    2018-03-15 09:30  28.48    4     0
16    2018-03-15 09:30  28.45   74     1
17    2018-03-15 09:30  28.45   25     0
18    2018-03-15 09:30  28.40   44     1
19    2018-03-15 09:30  28.45    6     0
20    2018-03-15 09:31  28.41   27     1
21    2018-03-15 09:31  28.45  167     0
22    2018-03-15 09:31  28.39  277     1
23    2018-03-15 09:31  28.39  344     0
24    2018-03-15 09:31  28.39   33     0
25    2018-03-15 09:31  28.38    4     1
26    2018-03-15 09:31  28.39   85     0
27    2018-03-15 09:31  28.38   27     0
28    2018-03-15 09:31  28.31   10     1
29    2018-03-15 09:31  28.31    4     0
...                ...    ...  ...   ...
3867  2018-03-15 14:55  28.41   12     0
3868  2018-03-15 14:55  28.41   26     0
3869  2018-03-15 14:55  28.40   19     1
3870  2018-03-15 14:55  28.40   20     0
3871  2018-03-15 14:55  28.40    8     0
3872  2018-03-15 14:55  28.40    9     0
3873  2018-03-15 14:55  28.40    2     0
3874  2018-03-15 14:55  28.40   34     0
3875  2018-03-15 14:55  28.40   40     0
3876  2018-03-15 14:56  28.40   57     0
3877  2018-03-15 14:56  28.36   16     1
3878  2018-03-15 14:56  28.40   12     0
3879  2018-03-15 14:56  28.39   20     2
3880  2018-03-15 14:56  28.40   16     0
3881  2018-03-15 14:56  28.40   13     0
3882  2018-03-15 14:56  28.37   17     1
3883  2018-03-15 14:56  28.39   57     0
3884  2018-03-15 14:56  28.39    7     0
3885  2018-03-15 14:56  28.38    3     1
3886  2018-03-15 14:56  28.37    1     0
3887  2018-03-15 14:56  28.36   31     1
3888  2018-03-15 14:56  28.37   39     1
3889  2018-03-15 14:56  28.37   24     1
3890  2018-03-15 14:56  28.36    4     1
3891  2018-03-15 14:56  28.37   36     0
3892  2018-03-15 14:56  28.37   11     0
3893  2018-03-15 14:56  28.36   57     1
3894  2018-03-15 14:57  28.36   96     0
3895  2018-03-15 14:57  28.36   35     2
3896  2018-03-15 15:00  28.35  836     2

[3897 rows x 4 columns]

In [12]:
df= ts.get_realtime_quotes('300433')

In [17]:
float(df['price'].values[0])

28.35

In [20]:
for i in debt['scode']:
    print i

002542
000623
000783
002548
300568
603618
603989
601966
002008
601857
300601
600908
002807
601128
300409
601929
002658
600372
002472
600863
002078
002100
002460
300059
300168
300197
002815
603738
002772
300433
002728
002142
002284
002707
002562
600183
300388
600845
002273
600566
603822
002318
601127
002527
601012
002597
601222
002271
601211
002279
000700
600350
002753
601311
601818
002325
000861
002496
601199
002510
600004
002245
601238
600998
600755
600031
300058
601601
600170
600109
600271
600535
601727
600185
002241
601336
603993
600023
601929
002491
600067
600875
002391
600109
002408
002318
601139
601318
000425
600820
002185
002065
600016
002347
000099
600085
600219
601989
600356
600795
600026
002031
000089
600674
600028
000887
600886
600798
600037
000729
601398
002233
000630
601988
000731
600481
600859
600966
000969
600352
600558
600815
600839
600362
600782
600068
600019
600518
600795
600219
000528
600600
600368
600018
600028
000063
600269
600428
000572
600104
600598
000709
600017
600227
600548
600971
600567
600026
000960
600078
600005
000717
600096
002031
600500
000629
600232
600808
600398
600423
600325
600010
600036
600219
000002
000488
000822
000937
000932
600874
600317
600037
600418
000069
000959
600001
600196
600096
000936
600117
600795
600236
600567
600726
000630
000930
600177
600016
000629
000729
000301
600087
000002
600220
000898
600009
000301
600301
600019
600488
600021
000839
000009
000024